version: "3.0"
services:

  msregister:
    container_name: msregistercore
    image: harbor.ukserp.ac.uk:443/ms-register/msregistercore:latest
#    environment:
#      - ConnectionStrings__DefaultConnection=${CONN}
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgresql:
    image: docker.io/bitnami/postgresql:latest
    restart: always
    container_name: postgres
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=mscore
      - POSTGRESQL_USERNAME=msproject
      - POSTGRESQL_DATABASE=letmein
    ports:
      - "32769:5432"
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  adminer:
#    image: harbor.chi.swan.ac.uk/nrda-v2/adminer:latest  # wodby/adminer:latest
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - "32767:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=mscore
    healthcheck:
      test: [ "CMD", "nc", "-z", "adminer", "9000" ]
      timeout: 45s
      interval: 10s
      retries: 10


volumes:
  postgresql_data:
    driver: local