version: "3.0"
services:

  msregister:
    container_name: msregistercore
    image: harbor.ukserp.ac.uk:443/ms-register/msregistercore:latest
#    environment:
#      - ConnectionStrings__DefaultConnection=${CONN}
    ports:
      - 8080:8080
    depends_on:
      - postgres


  postgresql:
    image: docker.io/bitnami/postgresql:latest
    restart: always
    container_name: postgres
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      #- POSTGRESQL_DATABASE=mscore
      - POSTGRESQL_USERNAME=msproject
      - POSTGRESQL_PASSWORD=letmein
    ports:
      - "32769:5432"
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  adminer:
#    image: harbor.chi.swan.ac.uk/nrda-v2/adminer:latest  # wodby/adminer:latest
    image: adminer:latest
    restart: always
    container_name: adminer
    ports:
      - "32767:8080"
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=psql
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=mscore
    healthcheck:
      test: [ "CMD", "nc", "-z", "adminer", "9000" ]
      timeout: 45s
      interval: 10s
      retries: 10

  #graphql-engine:
  #  image: hasura/graphql-engine:v2.10.1
  #  ports:
  #  - "8000:8080"
  #  depends_on:
  #  - "postgres"
  #  restart: always
  #  environment:
  #    ## postgres database to store Hasura metadata
  #    HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://msproject:letmein@postgres:5432/postgres
  #    ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
  #    PG_DATABASE_URL: postgres://msproject:letmein@postgres:5432/postgres
  #    ## enable the console served by server
  #    HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
  #    ## enable debugging mode. It is recommended to disable this in production
  #    HASURA_GRAPHQL_DEV_MODE: "true"
  #    HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  #    ## uncomment next line to set an admin secret
  #    # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

volumes:
  postgresql_data:
    driver: local