version: "3.0"
services:

  msregister:
    container_name: msregistercore
    image: msregistercore:latest
    environment:
      - ConnectionStrings__DefaultConnection=${CONN}
    ports:
      - 80:80