version: "3.0"
services:

  msregister:
    container_name: msregistercore
    image: msregister:latest
    environment:
      - ConnectionStrings__DefaultConnection=Server=(localdb)\\mssqllocaldb;Database=ms-core;Trusted_Connection=True;MultipleActiveResultSets=true
    ports:
      - 80:80