// <auto-generated />
using System;
using MSRegister_CoRe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MSRegister_CoRe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MSRegister_CoRe.Models.Root", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DominantHand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Root");
                });

            modelBuilder.Entity("MSRegister_CoRe.Models.Score", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentScore")
                        .HasColumnType("int");

                    b.Property<string>("DeviceOrientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Question")
                        .HasColumnType("int");

                    b.Property<string>("ScoreStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolChoice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TestID")
                        .HasColumnType("int");

                    b.Property<string>("TimeRemaining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoiceCommand")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("TestID");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("MSRegister_CoRe.Models.Test", b =>
                {
                    b.Property<int>("TestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EndStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.Property<int?>("RootID")
                        .HasColumnType("int");

                    b.Property<int>("SuccessfulAnswers")
                        .HasColumnType("int");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.HasKey("TestID");

                    b.HasIndex("RootID");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("MSRegister_CoRe.Models.Score", b =>
                {
                    b.HasOne("MSRegister_CoRe.Models.Test", null)
                        .WithMany("Scores")
                        .HasForeignKey("TestID");
                });

            modelBuilder.Entity("MSRegister_CoRe.Models.Test", b =>
                {
                    b.HasOne("MSRegister_CoRe.Models.Root", null)
                        .WithMany("Tests")
                        .HasForeignKey("RootID");
                });

            modelBuilder.Entity("MSRegister_CoRe.Models.Root", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("MSRegister_CoRe.Models.Test", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
